# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 922ee3222c858912bc79a7eeff942b6e65296112ab5af6dee085ab4219939fe47cb7371ee528357232114859cdcc5d288d729b033c127391b0648bddb5e1453d

test:
  secret_key_base: 048adfdca24ec00f679d89d882064cc2a00fa2129687d0f0e608f903036b06d153a82089fa0af14ae915555d11e47435ed808696108b8943d625c967287955f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
